spring.application.name=pet_pode_back

# Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d3dhc4er433s73eac9cg-a.oregon-postgres.render.com/banco_petpode
spring.datasource.username=banco_petpode_user
spring.datasource.password=O0VRC8VjXU78v5Xr2u4wnQwAsYAw7RwP
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


sendgrid.api.key=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
cloudinary.cloud_name=dbclo0rtc
cloudinary.api_key=286567313356239
cloudinary.api_secret=spTt2Kw3G5OUvApiKudAQkAATNs


# (Remova ou comente as linhas abaixo pois não usa mais SMTP)
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=petpodeoficial@gmail.com
# spring.mail.password=jajsavhzxprdtyrr
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# (Opcional: remover logs de debug do antigo sistema de email)
# logging.level.org.springframework.mail=DEBUG
# logging.level.org.apache.commons.mail=DEBUG
# logging.level.org.apache.james=DEBUG

# Server
server.port=8080
