spring.application.name=pet_pode_back

# Database
spring.datasource.url=jdbc:postgresql://dpg-d3dhc4er433s73eac9cg-a.oregon-postgres.render.com/banco_petpode
spring.datasource.username=banco_petpode_user
spring.datasource.password=O0VRC8VjXU78v5Xr2u4wnQwAsYAw7RwP
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000


sendgrid.api.key=${APIK_SENDGRID}
cloudinary.cloud_name=${APIN_CLOUDINARY}
cloudinary.api_key=${APIK_CLOUDINARY}
cloudinary.api_secret=${APIS_CLOUDINARY}
sendgrid.api.url=https://api.sendgrid.com/v3/mail/send
sendgrid.from.email=petpodeoficial@gmail.com




# Server
server.port=8080
